version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"  # Expose Redis on the default port 6379
    volumes:
      - redis_data:/data  # Persist Redis data

volumes:
  redis_data:
